### ISSUE TITLE
[FR] 希望配置编辑能加入去除标题阴影开关 

### ISSUE THREAD

**Issue by zed7th** [lingfengyu-dreaming/siyuan-vscodelite-edit#13]
### Describe your feature here./在这里描述你的功能。

RT，个人不太喜欢标题样式的阴影效果，但是又想保留彩色的标题样式，希望能加上开关可选标题阴影效果

### 检查清单 - Check list

- [X] I have finished the title and deleted the hints. (keep the [FR] there)/我已经填好了标题并且删除了提示文本。(保留[FR]在原处)
- [X] I have clearly described my feature./我已经清楚地描述了我想要的功能。
- [X] I know it should be done by a theme./我知道这是主题应该完成的。
- [X] It isn't a plugin feature./这不是一个插件功能。
- [ ] I didn't check all the checkboxes and therefore I just checked all of them. Please close and tag this feature request./我没有检查所有的复选框，只是闭眼选中了所有复选框。请关闭并标记这个功能请求。
- [X] No plugin does this feature./没有插件完成这个功能。
- [X] Not too hard for a theme to complete this feature./这个功能对主题来说不难实现。

**Comment by lingfengyu-dreaming** [comment]
我明天考试，这几天做一下

**Comment by lingfengyu-dreaming** [comment]
你在移动端界面看标题前的图标正常吗？还是会分行显示图标和标题？电脑端的显示效果正常吗？
这个东西如果有问题准备一起修了，我发现自己的手机显示效果还有问题

**Comment by zed7th** [comment]
> 你在移动端界面看标题前的图标正常吗？还是会分行显示图标和标题？电脑端的显示效果正常吗？ 这个东西如果有问题准备一起修了，我发现自己的手机显示效果还有问题

我这边安卓端和 PC 端标题都是正常显示的，没有分行

**Comment by lingfengyu-dreaming** [comment]
> 我这边安卓端和 PC 端标题都是正常显示的，没有分行

怎么只有我自己有问题吗，我再挂着议题，等看别人有没有反馈吧，可能是我自己的环境出问题了

**Comment by lingfengyu-dreaming** [comment]
close as finished
