### ISSUE TITLE
1k下载

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [lingfengyu-dreaming/siyuan-vscodelite-edit#3]
庆祝主题达到1k下载
我尽快把配置文件赶出来
早就有思路了
等我期末考完找时间开工

**Comment by lingfengyu-dreaming** [comment]
几天不看就立刻2125下载了，感谢支持

**Comment by lingfengyu-dreaming** [comment]
已经3218下载了，我错过了3k的时刻

**Comment by emptylight370** [comment]
今天重新上架集市，我记得上次看下载量是3k6多，那么就按3k7进行加算了。感谢各位支持。

**Comment by emptylight370** [comment]
说实话我也不知道到底下载多少了，用标签统计了一下整个仓库的下载，发现已经5.6k下载了，没想错思源的下载是走GitHub的，不过怎么思源的统计和GitHub的统计不一样呢

**Comment by emptylight370** [comment]
大概是集市会时不时重新下载计算release的hash跟保存的hash比较，所以会时不时给release增加一个下载量。我去看看改成最新的下载量试试。后面应该只显示一个版本的下载量了。

**Comment by emptylight370** [comment]
重新达到了1145下载量，值得庆祝🎉

**Comment by emptylight370** [comment]
又达到2175下载量了，又是原主题的一半，感谢各位支持
现在更新频率不比以往，想做的功能又没办法完成，感觉快到上限了

**Comment by emptylight370** [comment]
又一次达到了3k下载量，体感上和之前的下载量一样了。

重新起航，感谢各位陪伴。

**Comment by emptylight370** [comment]
目前下载量4519，因为2.3.3刚刚发布还没有更新，后面能涨一点。准备过一两小时接着发布2.3.4版本，看看还有什么问题一并修了。刚才没修完就发版是我疏忽了。

**Comment by emptylight370** [comment]
目前下载量6202，涨幅很大

**Comment by emptylight370** [comment]
下载量6310了，涨这么快，我没更几个版本啊

**Comment by emptylight370** [comment]
下载量7145，这两个月就两个版本，好像新用户变多了

**Comment by emptylight370** [comment]
下载量7409

**Comment by emptylight370** [comment]
下载量8043
