### ISSUE TITLE
优化有序列表编号？

### ISSUE THREAD

**Issue by qingmushui** [lingfengyu-dreaming/siyuan-vscodelite-edit#4]
能不能帮忙优化有序列表编号例如
1.
  a.
     i.
这样，我代码能力有限，从其他几个主题修改的代码，都出现了与文字对应不齐的问题，如果可以告诉我如何修改也可以，感谢

**Comment by lingfengyu-dreaming** [comment]
可能需要插件实现这个功能，我不会在主题里调用代码添加插件按钮，应该需要单独的插件做这个功能
可以尝试一下为需要修改编号的列表添加一个自定义属性，然后对拥有这个自定义属性的列表项修改编号显示内容，（应该不会影响保存的文件内容，）同时还要计算列表序号并修改对应的编号
把这个功能和主题捆绑在一起我倒是不太行，不过我可以先试试插件

**Comment by lingfengyu-dreaming** [comment]
或者你的做法是想要列表项实现按照层级显示不同的标号吗，这个我倒是可以尝试跟主题的代码写在一起
比如
1. 示例
2. 1. 示例
3. 1. 1. 示例

**Comment by lingfengyu-dreaming** [comment]
我刚刚试了Savor有这个功能，你可以尝试看看Savor的代码，可能是CSS做的，我看HTML里面的内容是`1.`，显示是`i.`，可能没有用js调文本。。
我看了Savor的源码，就是没有用js，用的是CSS，我倒是可以直接抄过来。。。。。。。。。。这合适吗
