### ISSUE TITLE
停靠栏背景颜色

### ISSUE THREAD

**Issue by LunaNorth** [lingfengyu-dreaming/siyuan-vscodelite-edit#5]
大佬 ，主题更新到1.3.5 后 ，两边的停靠栏背景色和之前的背景色不同 ，这个有什么办法改回去吗 ，或者在主题设置里面增加这样的一个配置
![image](https://github.com/user-attachments/assets/5ef06eaf-71ae-45e2-9e29-fffbccff8c5d)

**Comment by lingfengyu-dreaming** [comment]
这个颜色是我尝试适配自定义背景插件所做的改变，在检测到自定义背景插件启用之后就会将dock栏的背景改成和整个body部分一样的颜色，不然用自己定义的颜色再加上插件调整透明度就会让停靠栏（dock栏）整个透明，如果背景图片颜色比较白还会看不见高亮的按钮。
这个是我当前版本实验性的妥协，你是没有启用插件也出现改变吗？不启用插件js脚本就不会动停靠栏啊，我还要检查下哪里出了问题。

**Comment by LunaNorth** [comment]
> 这个颜色是我尝试适配自定义背景插件所做的改变，在检测到自定义背景插件启用之后就会将dock栏的背景改成和整个body部分一样的颜色，不然用自己定义的颜色再加上插件调整透明度就会让停靠栏（dock栏）整个透明，如果背景图片颜色比较白还会看不见高亮的按钮。 这个是我当前版本实验性的妥协，你是没有启用插件也出现改变吗？不启用插件js脚本就不会动停靠栏啊，我还要检查下哪里出了问题。

找到原因了 ，这个好像是和替换背景图片插件有关 ，关了之后就显示正常了和之前几个版本一样，但是启动插件后停靠栏两侧就会出现改变了
![image](https://github.com/user-attachments/assets/87b69c2f-ad81-4d71-9e36-c6d83d49bcbd)

**Comment by lingfengyu-dreaming** [comment]
检测到背景插件启用之后就修改颜色，我记得还判断了有没有显示背景的，如果在插件设置里不显示背景也不会修改dock栏。
要不像cliffdark那样直接显示一个透明背景吧，到时候全靠背景图当背景，禁用插件重新加载就是原来的效果。

**Comment by lingfengyu-dreaming** [comment]
> 找到原因了 ，这个好像是和替换背景图片插件有关 ，关了之后就显示正常了和之前几个版本一样，但是启动插件后停靠栏两侧就会出现改变了
> ![image](https://github.com/user-attachments/assets/87b69c2f-ad81-4d71-9e36-c6d83d49bcbd)
> 

此事在主题介绍的更新日志中亦有记载
~~我只是没做开关~~

**Comment by LunaNorth** [comment]
> > 找到原因了 ，这个好像是和替换背景图片插件有关 ，关了之后就显示正常了和之前几个版本一样，但是启动插件后停靠栏两侧就会出现改变了
> > ![image](https://private-user-images.githubusercontent.com/93069355/373444002-87b69c2f-ad81-4d71-9e36-c6d83d49bcbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMDUxMDgsIm5iZiI6MTcyODAwNDgwOCwicGF0aCI6Ii85MzA2OTM1NS8zNzM0NDQwMDItODdiNjljMmYtYWQ4MS00ZDcxLTllMzYtYzZkODNkNDliY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDAxMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NjgwZTA4M2YxZTQyZWU1MjQxZjZlZGJlMTE2MGViMjEyM2E4NmE3YWIwNTBhYzg1OGU3M2IxMTI1NzI1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mpo9EopVmQB3_qIM5JSelv3yeya320ZIiwqYM3ai09c)
> 
> 此事在主题介绍的更新日志中亦有记载 ~我只是没做开关~

好的 ，谢谢啦

**Comment by lingfengyu-dreaming** [comment]
@LunaNorth 我发了一版更新，尽可能适配了背景插件，你看看效果如何，还有其他bug我晚点再修

**Comment by LunaNorth** [comment]
> @LunaNorth 我发了一版更新，尽可能适配了背景插件，你看看效果如何，还有其他bug我晚点再修

感谢大佬 ，停靠栏背景颜色已经正常了 。不过我有个疑问 ，就是这个刚出的替换背景图片适配的这个主题设置 ，如果把前景透明调到0之后 ，会不会不太方便阅读 ，上面的图片是直接使用的背景图插件 ，没有开启这个替换背景图适配 ，下面的图片是根据替换背景图适配调整的
![image](https://github.com/user-attachments/assets/1a8235c2-5bf7-4faa-aead-89414113364f)

![image](https://github.com/user-attachments/assets/c7ecd106-b780-4fdb-ac8f-a67c389da54b)

**Comment by lingfengyu-dreaming** [comment]
> 如果把前景透明调到0之后 ，会不会不太方便阅读

我在自己测试时在自己的各种背景图下显示效果都算不错，并且这个透明度实际上并不是全部透明的，那样就太影响阅读了。我实际上是固定了`#a0`这个透明度的，这样子边框的透明度可以和编辑器的透明度一致。如果你的背景图太影响可以打开插件设置里的背景虚化，或者就关闭适配使用插件的前景透明。
附上我自己的使用效果：
![image](https://github.com/user-attachments/assets/80d7507e-b851-4649-8a1e-3a0475e9a0a2)
我会考虑在显眼的地方建议使用背景虚化功能的。

**Comment by LunaNorth** [comment]
> > 如果把前景透明调到0之后 ，会不会不太方便阅读
> 
> 我在自己测试时在自己的各种背景图下显示效果都算不错，并且这个透明度实际上并不是全部透明的，那样就太影响阅读了。我实际上是固定了`#a0`这个透明度的，这样子边框的透明度可以和编辑器的透明度一致。如果你的背景图太影响可以打开插件设置里的背景虚化，或者就关闭适配使用插件的前景透明。 附上我自己的使用效果： ![image](https://private-user-images.githubusercontent.com/61617417/373581898-80d7507e-b851-4649-8a1e-3a0475e9a0a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzM4NzYsIm5iZiI6MTcyODAzMzU3NiwicGF0aCI6Ii82MTYxNzQxNy8zNzM1ODE4OTgtODBkNzUwN2UtYjg1MS00NjQ5LThhMWUtM2EwNDc1ZTlhMGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA5MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTc4NmYwYzM5MDMyN2M2OGQxZmRlNjlmYzE4NjY4NmYzNzViMmZmMmIxMTNlYzdkZTQ5ZDZkODdkMzU1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.25SDoodVrNbXlswBtOT9Y0Op2bEGytjt1sRRKh9O8x0) 我会考虑在显眼的地方建议使用背景虚化功能的。

这样看的话 ，确实很好看 ，应该是因为我把背景虚化给设成0的原因 ，而且这个主题也是从发布到现在我一直在用的 ，在这里感谢下主题大大了 ，不过也发现了个bug , 就是开启这个设置后 ，数据库显示会不太正常
![image](https://github.com/user-attachments/assets/8a9c3302-8f27-4893-971e-6abf26be63bb)

**Comment by lingfengyu-dreaming** [comment]
救命啊，怎么数据库没有背景啊，要不我手动加一个，还有哪里没有背景再帮我看看吧

**Comment by LunaNorth** [comment]
> 救命啊，怎么数据库没有背景啊，要不我手动加一个，还有哪里没有背景再帮我看看吧

好的 ，那我先对比着背景图插件进行看看

**Comment by lingfengyu-dreaming** [comment]
目前没发现别的问题了，嵌入块的背景要改成透明或半透明吗，还是直接不动了？

**Comment by LunaNorth** [comment]
这两处算吗 ，还有代码块背景 ，其它的暂时还未发现
![image](https://github.com/user-attachments/assets/71ec7ed4-b770-4a62-bddc-4b8ce173c440)

**Comment by LunaNorth** [comment]
> 目前没发现别的问题了，嵌入块的背景要改成透明或半透明吗，还是直接不动了？

改成透明的会不会好看点呢 ，就和背景图插件一样

**Comment by lingfengyu-dreaming** [comment]
> 这两处算吗 ，还有代码块背景 ，其它的暂时还未发现

设置背景是有意为之，其实现在用的是第三版实现，第二版可以让整个思源的背景透明，但是打开集市之后插件详情页的背景也透明了，很影响使用体验。
代码块的背景一定程度上受代码块主题的改变，我暂时不想动。还有其他本来自带背景的我再看看。

**Comment by LunaNorth** [comment]
> > 这两处算吗 ，还有代码块背景 ，其它的暂时还未发现
> 
> 设置背景是有意为之，其实现在用的是第三版实现，第二版可以让整个思源的背景透明，但是打开集市之后插件详情页的背景也透明了，很影响使用体验。 代码块的背景一定程度上受代码块主题的改变，我暂时不想动。还有其他本来自带背景的我再看看。

这样啊 ，我还以为是漏掉了呢！加油！主题大大

**Comment by lingfengyu-dreaming** [comment]
我把不透明的地方模仿插件加上了透明度，不知道现在体验如何，等集市合并之后试试呢

**Comment by LunaNorth** [comment]
刚体验了下 ，看着是比上个版本好了很多 ，要是右面的透明度和左边的一样是否会好一点呢 ，大佬也要早点睡啊✨
![image](https://github.com/user-attachments/assets/64214406-d648-40b9-8b1b-2fca1b9cefd1)

**Comment by emptylight370** [comment]
@LunaNorth 设置页面右边的透明度我刚刚修改到和左边一样了，晚点提交，这是预览效果

<img width="1606" height="982" alt="Image" src="https://github.com/user-attachments/assets/4e17038a-de14-4274-8051-7be3b6e70424" />

集市里面的集市包背景我没动（鼠标放上去会更透明一些，类似高亮效果），详情页面也没动（这个是靠不透明背景盖住下面的设置界面实现的，不能动）

**Comment by LunaNorth** [comment]
赞 ，一直在使用这款主题 ，真的很喜欢这款的🌸🌸🌸
