### ISSUE TITLE
标题无法居中显示

### ISSUE THREAD

**Issue by LunaNorth** [lingfengyu-dreaming/siyuan-vscodelite-edit#9]
> [!NOTE]  
> 主题版本：v1.4.8 ，  思源笔记版本：v3.1.10

问题描述：点击布局使标题显示居中后 ，没有反应 ，刚开始我以为是代码片段的问题 ，我把所有的代码片段关闭后发现还是没有反应 ，我换了其他主题试了下发现可以居中显示

![image](https://github.com/user-attachments/assets/6ad4ae54-7f91-4367-9dd8-59664049e606)

**Comment by lingfengyu-dreaming** [comment]
我去看看

**Comment by lingfengyu-dreaming** [comment]
可以修，等我把受影响的样式都改过来就可以发版

**Comment by LunaNorth** [comment]
> 可以修，等我把受影响的样式都改过来就可以发版

好的 ，麻烦了

**Comment by lingfengyu-dreaming** [comment]
前面用的代码是ai生的，现在是我自己调出来的，能跑就行

**Comment by lingfengyu-dreaming** [comment]
fix in 274a128a99e15347f7cfeb1bfd1af8f5a9aa3296
